version: "3.9"

services:
    sistema_gestao:
        build:
            context: .
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - sistema-gestao-network

    nginx:
        container_name: servidor-nginx
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8989:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - sistema-gestao-network

    mysql:
        container_name: banco-mysql
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - setup-data:/var/lib/mysql/
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3388:3306"
        networks:
            - sistema-gestao-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=banco-mysql
        ports:
            - "8899:80"
        networks:
            - sistema-gestao-network

networks:
    sistema-gestao-network:
        driver: bridge

volumes:
    setup-data:
        driver: local
# Doc. de utilização
# Para acessar phpMyAdmin no navegador: http://localhost:8899/
# Para acessar o Nginx (servidor) no navegador: http://localhost:8989/

# Informações do phpMyAdmin no arquivo
# Servidor: banco-mysql
# Usuário: ${DB_USERNAME}
# Senha: ${DB_PASSWORD}
